### ISSUE TITLE
cf create-service ... -c '{"clone-from":"NAME"}'  can't get the new added record

### ISSUE THREAD

**Issue by samdai** [cloudfoundry-community/patroni-boshrelease#17]
The steps to reproduce this issue:
(1) Run a spring sample project as below, then open it in browser, there are 29 records shown in browser.

```
git clone https://github.com/scottfrederick/spring-music
cd spring-music
./gradlew assemble
cf push
cf cs dingo-postgresql cluster spring-music-pg
cf bs spring-music spring-music-pg
cf restart spring-music
```

(2) Insert a new record from the UI.
(3) Wait for 10 minutes, then execute commands as below:

```
cf create-service dingo-postgresql cluster spring-music-pg-2 -c '{"clone-from":"spring-music-pg"}' 
cf unbind-service spring-music spring-music-pg
cf bs spring-music spring-music-pg-2
cf restage spring-music
```

(4) Open the application in the browser again, still only 29 records are shown in the UI, the new added records in step (2) is not shown in the UI.

**Comment by drnic** [comment]
This feature is on master branch but not yet in a final release. Can you confirm you built/uploaded from git repo?

On Sat, Aug 27, 2016 at 7:41 AM +1000, "sam" notifications@github.com wrote:

The steps to reproduce this issue:

(1) Run a spring sample project as below, then open it in browser, there are 29 records shown in browser.

git clone https://github.com/scottfrederick/spring-music
cd spring-music
./gradlew assemble
cf push
cf cs dingo-postgresql cluster spring-music-pg
cf bs spring-music spring-music-pg
cf restart spring-music

(2) Insert a new record from the UI.

(3) Wait for 10 minutes, then execute commands as below:

cf create-service dingo-postgresql cluster spring-music-pg-2 -c '{"clone-from":"spring-music-pg"}' 
cf unbind-service spring-music spring-music-pg
cf bs spring-music spring-music-pg-2
cf restage spring-music

(4) Open the application in the browser again, still only 29 records are shown in the UI, the new added records in step (2) is not shown in the UI.

**Comment by samdai** [comment]
The release I used is the latest release:https://api.github.com/repos/dingotiles/dingo-postgresql-release/releases/latest.  when I deployed the service, I used the code of master branch of git repo

**Comment by drnic** [comment]
We can leave this issue open if you like. The feature will be finished for next final release.

On Sat, Aug 27, 2016 at 10:26 AM +1000, "sam" notifications@github.com wrote:

The release I used is the latest release:https://api.github.com/repos/dingotiles/dingo-postgresql-release/releases/latest.  when I deployed the service, I used the code of master branch of git repo

**Comment by samdai** [comment]
thanks

**Comment by drnic** [comment]
@samdai I've cut https://github.com/dingotiles/dingo-postgresql-release/releases/tag/v0.10.0-rc.2 for you to trial the new `clone-from` feature.

**Comment by samdai** [comment]
thanks a lot.

**Comment by samdai** [comment]
I tried the new clone-from feature for version v0.10.0, but can't work, the error message is as below:

```
cf create-service dingo-postgresql cluster staging -c '{"clone-from":"spring-music-pg"}'
Creating service instance staging in org diego / space diego as admin...
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: Could not locate backup for service instance 'spring-music-pg'
```

I generated manifest file using the following command:

```
./templates/make_manifest warden upstream \
  templates/services-cluster-backup-s3.yml templates/jobs-etcd.yml tmp/backups.yml templates/cf.yml templates/integration-test.yml
```

**Comment by drnic** [comment]
Quick debug idea - the original service instance needs to be created after v0.10 is running
This is because we now look up the service instance name from cloud controller at the end of the async process and store it in the clusterdata object store.
If it can't be found then perhaps the service instance was created before we implemented this aspect for provisioning.

On Sun, Sep 11, 2016 at 12:24 AM +1000, "sam" notifications@github.com wrote:

I tried the new clone-from feature for version v0.10.0, but can't work, the error message is as below:

cf create-service dingo-postgresql cluster staging -c '{"clone-from":"spring-music-pg"}'
Creating service instance staging in org diego / space diego as admin...
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: Could not locate backup for service instance 'spring-music-pg'

I generated manifest file using the following command:

./templates/make_manifest warden upstream \
  templates/services-cluster-backup-s3.yml templates/jobs-etcd.yml tmp/backups.yml templates/cf.yml templates/integration-test.yml

**Comment by samdai** [comment]
the original service instance is created after v0.10 is running, I tried several times, got the same error. it looks like the service instance name is not saved in the clusterdata object store

**Comment by drnic** [comment]
Most errors in the logs will end in .error - search for that and see what you find. 
My next guess is the config for CF isn't working or not sufficient/not admin enough to access the space you're working in?

On Mon, Sep 12, 2016 at 12:01 AM +1000, "sam" notifications@github.com wrote:

the original service instance is created after v0.10 is running, I tried several times, got the same error. it looks like the service instance name is not saved in the clusterdata object store

**Comment by samdai** [comment]
the version of my cf release is v241, I tried dingo-postgresql-release v0.10.0 and v0.10.0-rc.2, got the sam e error: 
`Server error, status code: 502, error code: 10001, message: Service broker error: Could not locate backup for service instance 'spring-music-pg'`
When I run command "bosh run errand integration-test", the error is as below:

```
+ sleep 10
+ test-clone-from-latest-by-name dingo-postgresql cluster DP-8657493741 stored-value-DP-8657493741
+ service=dingo-postgresql
+ plan=cluster
+ name=DP-8657493741
+ expected_value_stored=stored-value-DP-8657493741
+ clone_name=clone-DP-8657493741
+ service_key=clone-DP-8657493741-creds
++ cf-create-service dingo-postgresql cluster clone-DP-8657493741 clone-DP-8657493741-creds -c '{"clone-from":"DP-8657493741"}'
+ cf create-service dingo-postgresql cluster clone-DP-8657493741 -c '{"clone-from":"DP-8657493741"}'
Creating service instance clone-DP-8657493741 in org system / space integration-test as admin...
FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: Could not locate backup for service instance 'DP-8657493741'
+ credentials=

[stderr]
+ exec

Errand 'integration-test' completed with error (exit code 1)
```

**Comment by drnic** [comment]
As above, can you look in the backend logs (specifically broker) for errors to figure out where the issue is? Does the broker have adequate permissions to connect to CF (to get the service name?)

On Thu, Sep 15, 2016 at 9:01 AM -0500, "sam" notifications@github.com wrote:

the version of my cf release is v241, I tried dingo-postgresql-release v0.10.0 and v0.10.0-rc.2, got the sam e error: 

Server error, status code: 502, error code: 10001, message: Service broker error: Could not locate backup for service instance 'spring-music-pg'

When I run command "bosh run errand integration-test", the error is as below:
- sleep 10
- test-clone-from-latest-by-name dingo-postgresql cluster DP-8657493741 stored-value-DP-8657493741
- service=dingo-postgresql
- plan=cluster
- name=DP-8657493741
- expected_value_stored=stored-value-DP-8657493741
- clone_name=clone-DP-8657493741
- service_key=clone-DP-8657493741-creds
  ++ cf-create-service dingo-postgresql cluster clone-DP-8657493741 clone-DP-8657493741-creds -c '{"clone-from":"DP-8657493741"}'
- cf create-service dingo-postgresql cluster clone-DP-8657493741 -c '{"clone-from":"DP-8657493741"}'
  Creating service instance clone-DP-8657493741 in org system / space integration-test as admin...
  FAILED
  Server error, status code: 502, error code: 10001, message: Service broker error: Could not locate backup for service instance 'DP-8657493741'
- credentials=

[stderr]
- exec

Errand 'integration-test' completed with error (exit code 1)

**Comment by samdai** [comment]
I just ran `cf create-service dingo-postgresql cluster spring-music-pg-2 -c '{"clone-from":"spring-music-pg"}'` again, found the following error in the syslog:

```
Sep 15 07:47:26 0.router.dingo-postgresql-warden-upstream broker.stderr.log:  {"timestamp":"1473950846.594742060","source":"dingo-postgresql-broker","message":"dingo-postgresql-broker.provision.lookup-service-name.error","log_level":2,"data":{"error":"Could not locate backup for service instance 'spring-music-pg'","instance-id":"a2026903-b5c9-45eb-92dd-5e89c553e6f0","session":"4"}}
Sep 15 07:47:26 0.router.dingo-postgresql-warden-upstream broker.stderr.log:  {"timestamp":"1473950846.594801903","source":"dingo-postgresql-broker","message":"dingo-postgresql-broker.provision.unknown-error","log_level":2,"data":{"error":"Could not locate backup for service instance 'spring-music-pg'","instance-id":"a2026903-b5c9-45eb-92dd-5e89c553e6f0","provision-details":{"organization_guid":"a99f8a17-245b-4edd-8d47-b65d7bec3a86","plan_id":"1545e30e-6dc3-11e5-826a-6c4008a663f0","service_id":"beb5973c-e1b2-11e5-a736-c7c0b526363d","space_guid":"378c11f8-af0a-4f58-bf72-387fed90f786","parameters":{"clone-from":"spring-music-pg"}},"session":"3"}}
```

here instance id is "a2026903-b5c9-45eb-92dd-5e89c553e6f0", but when I run command `cf service spring-music-pg --guid`, the id is "5392743c-8ea4-4adc-8e04-171c6344a50c", why these two id are different?

**Comment by samdai** [comment]
In broker.stderr.log of vm router 0, I found the following error in log, it said "Cannot lookup Service Name for %!d(structs.ClusterID=5392743c-8ea4-4adc-8e04-171c6344a50c) without Cloud Foundry credentials", where to configure the Cloud Foundry credentials for broker?

```
{"timestamp":"1473946609.526786804","source":"dingo-postgresql-broker","message":"dingo-postgresql-broker.cluster-data.member-data.get","log_level":2,"data":{"err":"100: Key not found (/service/5392743c-8ea4-4adc-8e04-171c6344a50c/members/b4c97733-4a7c-4c3a-a237-ca6e61a80245) [1919]","error":"100: Key not found (/service/5392743c-8ea4-4adc-8e04-171c6344a50c/members/b4c97733-4a7c-4c3a-a237-ca6e61a80245) [1919]","instance-id":"5392743c-8ea4-4adc-8e04-171c6344a50c","member":"b4c97733-4a7c-4c3a-a237-ca6e61a80245","not-found-yet":true}}
{"timestamp":"1473946635.523642540","source":"dingo-postgresql-broker","message":"dingo-postgresql-broker.provision.backup-name.error","log_level":2,"data":{"action-required":"Fix issue and run errand/script to update clusterdata backups to include service names","error":"Cannot lookup Service Name for %!d(structs.ClusterID=5392743c-8ea4-4adc-8e04-171c6344a50c) without Cloud Foundry credentials","instance-id":"5392743c-8ea4-4adc-8e04-171c6344a50c","session":"1404"}}
```

My setting for cf.yml is as below:

```
meta:
  cf:
    api_url: "api.bosh-lite.com"
    username: "admin"
    password: "admin"
    skip_ssl_validation: true

jobs:
- name: router
  properties:
    cf:
      api_url: (( grab meta.cf.api_url ))
      username: (( grab meta.cf.username ))
      password: (( grab meta.cf.password ))
      skip_ssl_validation: (( grab meta.cf.skip_ssl_validation ))
```

**Comment by samdai** [comment]
Found the reason, it looks like firewall or network issue, I used a aws vm to try it again, now clone from feature works

**Comment by drnic** [comment]
Awesome!

On Fri, Sep 16, 2016 at 3:42 AM -0500, "sam" notifications@github.com wrote:

Closed #17.

**Comment by drnic** [comment]
Actually it's not awesome - the sanity-test errand should have given nice errors saying it was having trouble with network connectivity at the start.
And I should have asked if you'd run the sanity-test errand successfully. Sorry - it might have gotten you to the network connectivity issue with Amazon S3.

On Fri, Sep 16, 2016 at 11:21 AM -0500, "Dr Nic Williams" drnicwilliams@gmail.com wrote:

Awesome!

On Fri, Sep 16, 2016 at 3:42 AM -0500, "sam" notifications@github.com wrote:

Closed #17.

**Comment by samdai** [comment]
when I ran the sanity-test errand, in step " Testing service move of containers to new cells", there is the following error:

```
test-move> {"description":"Unknown error: 'Failover status unknown'"}
test-move> {"description":"Unknown error: 'Failover status unknown'"}
test-move> {"description":"Unknown error: 'Failover status unknown'"}
test-move> {"description":"Unknown error: 'Failover status unknown'"}
test-move> {"description":"Unknown error: 'Failover status unknown'"}
test-move> final error state of cluster 
test-move>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
test-move>                                  Dload  Upload   Total   Spent    Left  Speed
...
test-move> Couldn't update service instance with 300s
```

in syslog, there is the following error:

```
Sep 16 18:44:24 122.84.164.94 docker/cf-708fb1dc-3723-436a-a637-dd588585e4c8: T-9455-backup> wal_e.worker.upload INFO MSG: Retrying send because of a socket error
Sep 16 18:44:24 122.84.164.94 docker/cf-708fb1dc-3723-436a-a637-dd588585e4c8: T-9455-backup> DETAIL: The socket error's message is 'The handshake operation timed out'. There have been 9 attempts to send the volume 0 so far.
```

**Comment by drnic** [comment]
Are there more errors before that (since it was the 9th attempt) indicating
that it couldn't upload WAL segments & base backups?

If you run sanity-test again does it work? (e.g. was it a corruption/quirk
of that one database cluster/docker container pair)

**Comment by samdai** [comment]
There is the following error before that(since it was the xth attempt) :

```
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> Traceback (most recent call last):
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> File "/usr/local/lib/python2.7/dist-packages/gevent/greenlet.py", line 534, in run
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> result = self._run(*self.args, **self.kwargs)
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/upload.py", line 50, in __call__
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> self.gpg_key_id)
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/worker_util.py", line 40, in do_lzop_put
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> k = blobstore.uri_put_file(creds, url, tf)
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> File "/usr/local/lib/python2.7/dist-packages/wal_e/blobstore/s3/s3_util.py", line 57, in uri_put_file
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> k.set_contents_from_file(fp, encrypt_key=True)
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 1293, in set_contents_from_file
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> chunked_transfer=chunked_transfer, size=size)
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 750, in send_file
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> chunked_transfer=chunked_transfer, size=size)
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> File "/usr/local/lib/python2.7/dist-packages/boto/s3/key.py", line 951, in _send_file_internal
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> query_args=query_args
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> File "/usr/local/lib/python2.7/dist-packages/boto/s3/connection.py", line 668, in make_request
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> retry_handler=retry_handler
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> retry_handler=retry_handler)
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1030, in _mexe
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> raise ex
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> SSLError: timed out
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni>
Sep 25 06:35:46 122.84.157.172 docker/cf-8351e101-68fa-4232-98a2-4c12c887afed: cb0342-patroni> <Greenlet at 0x7f21dd4e4410: <wal_e.worker.upload.WalUploader object at 0x7f21dd497ad0>(<wal_e.worker.pg.wal_transfer.WalSegment object at)> failed with SSLError
```

when run sanity-test , there is the following log:

```
test-failure-recovery> *
test-failure-recovery> *
test-failure-recovery> * Testing database restoration
test-failure-recovery> *
test-failure-recovery> *
test-failure-recovery> ++ curl -sf 10.244.21.6:4001/v2/keys/service/T-8921184741/wale-backup-list
test-failure-recovery> ++ jq -r .node.value
test-failure-recovery> ++ wc -l
test-failure-recovery> + backups_lines=1
test-failure-recovery> + set +x
test-failure-recovery> Waiting for first backups to be written 0
test-failure-recovery> ++ curl -sf 10.244.21.6:4001/v2/keys/service/T-8921184741/wale-backup-list
test-failure-recovery> ++ jq -r .node.value
test-failure-recovery> ++ wc -l
test-failure-recovery> + backups_lines=1
test-failure-recovery> + set +x
test-failure-recovery> Waiting for first backups to be written 1
test-failure-recovery> ++ curl -sf 10.244.21.6:4001/v2/keys/service/T-8921184741/wale-backup-list
test-failure-recovery> ++ jq -r .node.value
test-failure-recovery> ++ wc -l
test-failure-recovery> + backups_lines=1
test-failure-recovery> + set +x
test-failure-recovery> Waiting for first backups to be written 2
test-failure-recovery> ++ curl -sf 10.244.21.6:4001/v2/keys/service/T-8921184741/wale-backup-list
test-failure-recovery> ++ jq -r .node.value
test-failure-recovery> ++ wc -l
test-failure-recovery> + backups_lines=1
test-failure-recovery> + set +x
test-failure-recovery> Waiting for first backups to be written 3
test-failure-recovery> ++ curl -sf 10.244.21.6:4001/v2/keys/service/T-8921184741/wale-backup-list
test-failure-recovery> ++ jq -r .node.value
test-failure-recovery> ++ wc -l
test-failure-recovery> + backups_lines=1
test-failure-recovery> + set +x
test-failure-recovery> Waiting for first backups to be written 4
test-failure-recovery> ++ curl -sf 10.244.21.6:4001/v2/keys/service/T-8921184741/wale-backup-list
test-failure-recovery> ++ jq -r .node.value
test-failure-recovery> ++ wc -l
test-failure-recovery> + backups_lines=1
test-failure-recovery> + set +x
test-failure-recovery> Waiting for first backups to be written 5
test-failure-recovery> ++ curl -sf 10.244.21.6:4001/v2/keys/service/T-8921184741/wale-backup-list
test-failure-recovery> ++ jq -r .node.value
test-failure-recovery> ++ wc -l
test-failure-recovery> + backups_lines=1
test-failure-recovery> + set +x
test-failure-recovery> Waiting for first backups to be written 6
test-failure-recovery> ++ curl -sf 10.244.21.6:4001/v2/keys/service/T-8921184741/wale-backup-list
test-failure-recovery> ++ jq -r .node.value
test-failure-recovery> ++ wc -l
test-failure-recovery> + backups_lines=1
test-failure-recovery> + set +x
test-failure-recovery> Waiting for first backups to be written 7
test-failure-recovery> ++ curl -sf 10.244.21.6:4001/v2/keys/service/T-8921184741/wale-backup-list
test-failure-recovery> ++ jq -r .node.value
test-failure-recovery> ++ wc -l
test-failure-recovery> + backups_lines=1
test-failure-recovery> + set +x
test-failure-recovery> Waiting for first backups to be written 8
test-failure-recovery> ++ curl -sf 10.244.21.6:4001/v2/keys/service/T-8921184741/wale-backup-list
test-failure-recovery> ++ jq -r .node.value
test-failure-recovery> ++ wc -l
test-failure-recovery> + backups_lines=1
test-failure-recovery> + set +x
test-failure-recovery> Waiting for first backups to be written 9
test-failure-recovery> ++ curl -sf 10.244.21.6:4001/v2/keys/service/T-8921184741/wale-backup-list
test-failure-recovery> ++ jq -r .node.value
test-failure-recovery> ++ wc -l
test-failure-recovery> + backups_lines=1
test-failure-recovery> + set +x
test-failure-recovery> Waiting for first backups to be written 10
test-failure-recovery> ++ curl -sf 10.244.21.6:4001/v2/keys/service/T-8921184741/wale-backup-list
test-failure-recovery> ++ jq -r .node.value
test-failure-recovery> ++ wc -l
test-failure-recovery> + backups_lines=1
test-failure-recovery> + set +x
test-failure-recovery> Waiting for first backups to be written 11
test-failure-recovery> + [[ 1 -lt 2 ]]
test-failure-recovery> + echo 'No backups are being written'
test-failure-recovery> No backups are being written
test-failure-recovery> + exit 1

[stderr]
+ exec

Errand 'sanity-test' completed with error (exit code 1)
```
