### ISSUE TITLE
template file for aws

### ISSUE THREAD

**Issue by samdai** [cloudfoundry-community/patroni-boshrelease#18]
is there sample template file for aws? for example infrastructure-aws.yml, thanks

**Comment by drnic** [comment]
I'm rolling out 0.10.0 to our own AWS pipelines early next week and will extract AWS samples from that.

On Fri, Sep 2, 2016 at 10:17 AM +1000, "sam" notifications@github.com wrote:

is there sample template file for aws? for example infrastructure-aws.yml, thanks

**Comment by samdai** [comment]
thanks
