### ISSUE TITLE
sanity-test failed after dingo-postgresql-release update from v0.8.0 to v0.10.0

### ISSUE THREAD

**Issue by ishwarps** [cloudfoundry-community/patroni-boshrelease#20]
Hi,
The dingo-postgresql-release-0.8.0 was successfully run with sanity test case but after upgrading to 0.10.0. The sanity-test giving following error.

test-move> + echo 'Cluster should have moved its nodes to different backend cells'
test-move> Cluster should have moved its nodes to different backend cells
test-move> + exit 1
[stderr]
- exec
  Errand 'sanity-test' completed with error (exit code 1)

I have attached here screen shot here.
![dingotest_fail](https://cloud.githubusercontent.com/assets/7974404/18741333/3ae6a892-80cc-11e6-98dd-46a2a2ba30c8.png)

Thanks in advanced

**Comment by drnic** [comment]
Do you have four cells (two in two AZs)? We might not have a nice error or "skipping test-move as not enough cells".

On Thu, Sep 22, 2016 at 10:27 AM +0200, "ishwar1987" notifications@github.com wrote:

Hi,

The dingo-postgresql-release-0.8.0 was successfully run with sanity test case but after upgrading to 0.10.0. The sanity-test giving following error.

test-move> + echo 'Cluster should have moved its nodes to different backend cells'

test-move> Cluster should have moved its nodes to different backend cells

test-move> + exit 1

[stderr]

exec
Errand 'sanity-test' completed with error (exit code 1)

I have attached here screen shot here.

Thanks in advanced

**Comment by ishwarps** [comment]
Hi,
We have  four cells in two AZs(four in each two AZs). I am attaching log file here for more logs.
[DingoTestCaseError.txt](https://github.com/dingotiles/dingo-postgresql-release/files/486997/DingoTestCaseError.txt)

**Comment by drnic** [comment]
Hmm it seems to think there is only two cells:
test-move> available_cells_guids: 10.0.124.7test-move> 10.0.125.6test-move> service_cells_guids: 10.0.124.7test-move> 10.0.125.6test-move> alternate_cell_guids: test-move> cf update-service parameters: {"cells":[]}
Perhaps check your deployment manifest and check all 8 cell_guids are being advertised.

On Thu, Sep 22, 2016 at 12:18 PM +0200, "ishwar1987" notifications@github.com wrote:

Hi,

We have  four cells in two AZs. I am attaching log file here for more logs.

DingoTestCaseError.txt

**Comment by ishwarps** [comment]
Hi,
Thanks for replay. It means that i have to increase the cell? and  How many required?

**Comment by drnic** [comment]
Check what you have for `properties.servicebroker.backends.machines` for the `router`:

https://github.com/dingotiles/dingo-postgresql-release/blob/master/templates/infrastructure-warden.yml#L25-L28

Specifically its the broker job template https://github.com/dingotiles/dingo-postgresql-release/blob/master/jobs/broker/spec#L40-L47

**Comment by drnic** [comment]
We are progressively moving towards the broker dynamically discovering the backend cells, rather than having them statically described via bosh deployment manifest. Currently we need to update this property when we add new cells.

**Comment by drnic** [comment]
FYI, this configuration ends up in broker.yml here: https://github.com/dingotiles/dingo-postgresql-release/blob/master/jobs/broker/templates/config/broker.yml.erb#L8-L17 and then turns up in the broker configuration as https://github.com/dingotiles/dingo-postgresql-broker/blob/master/config/config.go#L13-L50

**Comment by ishwarps** [comment]
Thanks, we got it. Now it is working.

**Comment by drnic** [comment]
Awesome!

On Fri, Sep 23, 2016 at 7:51 AM +0200, "ishwar1987" notifications@github.com wrote:

Closed #20.
