### ISSUE TITLE
How to get sql dump file of my database services

### ISSUE THREAD

**Issue by ishwarps** [cloudfoundry-community/patroni-boshrelease#24]
Hi,
I need the sql dump file of my database services As i need to execute locally my application with same data.
Is there any way i can get the sql dump file?.

Regards
Ishwar

**Comment by drnic** [comment]
With the binding URI you can run pg_dump (and similar commands) to get the DB contents as SQL.
Let me know how it goes.



		_____________________________

**Comment by ishwarps** [comment]
Hi,
Thanks a lot. it is working.

Regards
Ishwar
