### ISSUE TITLE
What about the "links-and-cloud-config" work in progress?

### ISSUE THREAD

**Issue by bgandon** [cloudfoundry-community/patroni-boshrelease#32]
Hi,

I'm interested in deploying dingo-pg with Bosh 2.
So, the `links-and-cloud-config` branch is of great interest and I could contribute to it.

In this regards, I would like to know some more about that branch:

- Do plan to finish this work? Do you plan to merge it in the master branch and cut a new final version?
- Is it usable? What was still to be done for it to work?

Thanks for your answers and guidance!

**Comment by drnic** [comment]
Hey @bgandon currently this project is not actively developed nor supported. Over the year and half of development it didn't acquire a lot of users as an OSS nor a commercial product (I even did two multi-week road trips in early 2017 around USA to visit Pivotal offices to show it off).

Any future version of it would have a different name, different implementation of scheduling (maybe docker-boshrelease again, maybe cfcr/kubo/k8s, maybe bosh on-demand github.com/cppforlife/bosh-generic-sb-release), different implementation of PostgreSQL configuration (maybe https://github.com/zalando/patroni again, maybe https://www.habitat.sh/, switching to https://github.com/wal-g/wal-g to replace https://github.com/wal-e/wal-e, and definitely moving to PostgreSQL 10).
