### ISSUE TITLE
ETCD Missconfigured Error

### ISSUE THREAD

**Issue by Rohitverma47** [cloudfoundry-community/patroni-boshrelease#7]
It is giving me an error when I am adding the S3 storage feature,the Broker is getting updated but when  trying to create an instance for the service it is showing me and error (Server error, status code: 502, error code: 10001, message: Service broker error: exit status 1) and when checked the logs for broker is showing ETCD cluster is miss configured or unavailable.
And if i am not adding the S3 section in the manifest file it is working fine the services are getting created. 
Would you please help me with that

**Comment by bodymindarts** [comment]
This sounds strange. Could it be that the s3 creds you added don't have the correct permissions?

**Comment by Rohitverma47** [comment]
Thanks @bodymindarts

**Comment by gunakr** [comment]
so we have issued fixed ? @Rohitverma47

**Comment by drnic** [comment]
Closing. Re-open if you've got some additional info to help us reproduce it.

**Comment by Rohitverma47** [comment]
Sure you can @drnic
